# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'RNPhotoEditor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNPhotoEditor
  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('iOSPhotoEditor')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5'
        end
      end
    end
  end

end
